/* LOGIN */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

/* SIGN UP */
export const SIGN_REQUEST = "SIGN_REQUEST";
export const SIGN_SUCCESS = "SIGN_SUCCESS";
export const SIGN_FAILED = "SIGN_FAILED";

/* FORGET PASSWORD */
export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILED = "FORGET_PASSWORD_FAILED";

/* FETCHING RESULT */
export const IS_FETCHING_REQUEST = "IS_FETCHING_REQUEST";
export const IS_FETCHING_COMPLETE = "IS_FETCHING_COMPLETE";

/* LOG OUT */
export const LOGOUT = "LOGOUT";

/* STORE TOKEN IN REDUX */
export const SAVE_TOKEN = "SAVE_TOKEN";

/* UNAUTHORIZED */
export const UNAUTHORIZED_USER = "UNAUTHORIZED_USER";