/* CREATE BOOKING */
export const CREATE_BOOKING_REQUEST = "CREATE_BOOKING_REQUEST";
export const CREATE_BOOKING_SUCCESS = "CREATE_BOOKING_SUCCESS";
export const CREATE_BOOKING_FAILED = "CREATE_BOOKING_FAILED";

/* GET_SELLERS*/
export const FETCH_SELLERS_REQUEST = "FETCH_SELLERS_REQUEST";
export const FETCH_SELLERS_SUCCESS = "FETCH_SELLERS_SUCCESS";
export const FETCH_SELLERS_FAILED = "FETCH_SELLERS_FAILED";