/* GET_MY_BOOKINGS*/
export const FETCH_MY_BOOKINGS_REQUEST = "FETCH_MY_BOOKINGS_REQUEST";
export const FETCH_MY_BOOKINGS_SUCCESS = "FETCH_MY_BOOKINGS_SUCCESS";
export const FETCH_MY_BOOKINGS_FAILED = "FETCH_MY_BOOKINGS_FAILED";

/* CANCEL BOOKING REQUEST*/ 
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";
export const CANCEL_BOOKING_FAILED = "CANCEL_BOOKING_FAILED";
